#!/bin/sh
git config --global push.default tracking
git config --global alias.co checkout
git config --global alias.st 'status -s'
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.up 'pull --rebase'
git config --global alias.qlog 'whatchanged --oneline --decorate --color'
git config --global branch.autosetuprebase always
